# Healthcare Dataset Analysis

In [2]:
!pip install pandas 
!pip install sqlalchemy
!pip install python-dotenv psycopg2

Requirement already satisfied: pandas in c:\users\ankit\anaconda3\lib\site-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\ankit\anaconda3\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\ankit\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\ankit\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\ankit\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\ankit\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Requirement already satisfied: sqlalchemy in c:\users\ankit\anaconda3\lib\site-packages (2.0.34)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\ankit\anaconda3\lib\site-packages (from sqlalchemy) (4.11.0)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\ankit\anaconda3\lib\site-packages (from sqlalchemy) (3.0.1)
Requirement already satisfied: python-dotenv in c:\users\ankit\anaconda3\lib\site-packages (0.21.0)
Requirement already satisfied: psycopg2 in c:\users\ankit\anaconda3\lib\site-packages (2.9.10)

In [3]:
import pandas as pd
from sqlalchemy import create_engine
from dotenv import load_dotenv
import psycopg2
import os

In [4]:
df = pd.read_excel('../data/Healthcare.xlsx')

In [5]:
df.head()

,Name,Age,Age_Group,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby JacksOn,30,21-30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.2813,328,Urgent,2024-02-02,Paracetamol,Normal
1,LesLie TErRy,62,60,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.3273,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,DaNnY sMitH,76,60,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.0961,205,Emergency,2022-10-07,Aspirin,Normal
3,andrEw waTtS,28,21-30,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.7824,450,Elective,2020-12-18,Ibuprofen,Abnormal
4,adrIENNE bEll,43,41-50,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.3178,458,Urgent,2022-10-09,Penicillin,Abnormal

In [19]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')

df.head()

,name,age,age_group,gender,blood_type,medical_condition,date_of_admission,doctor,hospital,insurance_provider,billing_amount,room_number,admission_type,discharge_date,medication,test_results
0,Bobby JacksOn,30,21-30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.2813,328,Urgent,2024-02-02,Paracetamol,Normal
1,LesLie TErRy,62,60,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.3273,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,DaNnY sMitH,76,60,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.0961,205,Emergency,2022-10-07,Aspirin,Normal
3,andrEw waTtS,28,21-30,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.7824,450,Elective,2020-12-18,Ibuprofen,Abnormal
4,adrIENNE bEll,43,41-50,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.3178,458,Urgent,2022-10-09,Penicillin,Abnormal

In [20]:
load_dotenv()

True

In [21]:
db_url = os.getenv('URL')

In [22]:
engine = create_engine(db_url)

In [24]:
df.to_sql('data',engine,if_exists='replace',index=False)

500